export enum Icon {
  ArrowBack = 'arrow_back',
  ArrowForward = 'arrow_forward',
  Donate = 'donate',
  Facebook = 'facebook',
  Instagram = 'instagram',
  Issue = 'issue',
  Line = 'line',
  Mail = 'mail',
  News = 'news',
  Twitter = 'twitter',
  User = 'user',
  Youtube = 'youtube',
  Cancel = 'cancel',
}
